import { HttpError, joinUrl, request } from './http'
import { absoluteUrl, firstNonEmpty, parseChannelIdFromPath, parseVideoIdFromPath, toInt, UNKNOWN } from './mapping'
import type {
  ChannelInfo,
  CommentItem,
  CommentsPage,
  Paged,
  PlaylistInfo,
  ProviderApi,
  Subtitle,
  VideoDetail,
  VideoFormat,
  VideoListItem,
} from './types'

interface PipedInstanceRef {
  label: string
  apiUrl: string
}

interface RawSearchItem {
  url?: string
  type?: string
  title?: string
  thumbnail?: string
  uploaderName?: string
  uploaderUrl?: string
  uploaderAvatar?: string
  uploaderVerified?: boolean
  duration?: number
  views?: number
  viewsText?: string
  uploadedDate?: string
  shortDescription?: string
  isShort?: boolean
  live?: boolean
}

interface RawPage {
  items?: RawSearchItem[]
  nextpage?: string | null
}

interface RawStream {
  url?: string
  bitrate?: number
  codec?: string
  format?: string
  mimeType?: string
  quality?: string
  videoOnly?: boolean
  fps?: number
  height?: number
  width?: number
  audioQuality?: string
  initStart?: number
  itag?: number
}

interface RawStreams {
  title?: string
  description?: string
  thumbnailUrl?: string
  duration?: number
  views?: number
  likes?: number
  dislikes?: number
  uploadDate?: string
  uploader?: string
  uploaderUrl?: string
  uploaderAvatar?: string
  uploaderVerified?: boolean
  subCountText?: string
  livestream?: boolean
  hls?: string | null
  proxyUrl?: string
  videoStreams?: RawStream[]
  audioStreams?: RawStream[]
  subtitles?: { name?: string; code?: string; url?: string; autoGenerated?: boolean }[]
  relatedStreams?: RawSearchItem[]
}

interface RawChannel {
  id?: string
  name?: string
  avatarUrl?: string
  bannerUrl?: string
  description?: string
  subscriberCount?: number
  verified?: boolean
  nextpage?: string | null
  relatedStreams?: RawSearchItem[]
}

interface RawPlaylist {
  name?: string
  thumbnailUrl?: string
  bannerUrl?: string
  description?: string
  uploader?: string
  uploaderUrl?: string
  uploaderAvatar?: string
  videos?: number
  nextpage?: string | null
  relatedStreams?: RawSearchItem[]
}

interface RawComment {
  commentId?: string
  author?: string
  commentText?: string
  commentedTime?: string
  commentorUrl?: string
  thumbnail?: string
  verified?: boolean
  likeCount?: number
  hearted?: boolean
  pinned?: boolean
  creatorReplied?: boolean
}

interface RawComments {
  comments?: RawComment[]
  disabled?: boolean
  nextpage?: string
}

const MONTHS: Record<string, number> = {
  jan: 0, feb: 1, mar: 2, apr: 3, may: 4, jun: 5,
  jul: 6, aug: 7, sep: 8, oct: 9, nov: 10, dec: 11,
}

export function relativeToTimestamp(text: string | undefined): number {
  if (!text) return UNKNOWN
  const value = text.trim().toLowerCase()
  if (value === '') return UNKNOWN

  const direct = Date.parse(value)
  if (Number.isFinite(direct)) return Math.floor(direct / 1000)

  const isoMatch = value.match(/^(\d{4})-(\d{2})-(\d{2})/)
  if (isoMatch) return Math.floor(Date.UTC(+isoMatch[1], +isoMatch[2] - 1, +isoMatch[3]) / 1000)

  const amountMatch = value.match(/(\d+)\s*(second|minute|hour|day|week|month|year)/)
  if (amountMatch) {
    const amount = Number(amountMatch[1])
    const unit = amountMatch[2]
    const now = Date.now()
    const table: Record<string, number> = {
      second: 1000,
      minute: 60_000,
      hour: 3_600_000,
      day: 86_400_000,
      week: 604_800_000,
      month: 2_592_000_000,
      year: 31_536_000_000,
    }
    return Math.floor((now - amount * (table[unit] ?? 0)) / 1000)
  }

  const monthMatch = value.match(/([a-z]{3})[a-z]*\s+(\d{1,2})/)
  if (monthMatch && MONTHS[monthMatch[1]] !== undefined) {
    return Math.floor(Date.UTC(new Date().getUTCFullYear(), MONTHS[monthMatch[1]], Number(monthMatch[2])) / 1000)
  }

  return UNKNOWN
}

function mapSearchItem(raw: RawSearchItem): VideoListItem {
  const id = parseVideoIdFromPath(raw.url)
  const duration = toInt(raw.duration, UNKNOWN)
  const views = toInt(raw.views ?? raw.viewsText, UNKNOWN)
  return {
    id,
    title: firstNonEmpty(raw.title, 'Untitled'),
    thumbnail: firstNonEmpty(raw.thumbnail),
    duration,
    views,
    viewsText: firstNonEmpty(raw.viewsText),
    publishedText: firstNonEmpty(raw.uploadedDate),
    published: relativeToTimestamp(raw.uploadedDate),
    uploaderName: firstNonEmpty(raw.uploaderName),
    uploaderId: parseChannelIdFromPath(raw.uploaderUrl),
    uploaderAvatar: firstNonEmpty(raw.uploaderAvatar),
    uploaderVerified: Boolean(raw.uploaderVerified),
    live: Boolean(raw.live) || duration === 0,
    isShort: Boolean(raw.isShort),
  }
}

function mapVideoFormat(raw: RawStream, index: number, base: string, kind: 'video' | 'audio'): VideoFormat {
  const height = kind === 'video' ? toInt(raw.height, 0) : 0
  const width = kind === 'video' ? toInt(raw.width, 0) : 0
  const codec = firstNonEmpty(raw.codec)
  const quality = firstNonEmpty(raw.quality)
  const resolvedHeight = height > 0 ? height : (Number.parseInt(quality, 10) || 0)
  return {
    itag: toInt(raw.itag, index + 1),
    url: absoluteUrl(firstNonEmpty(raw.url), base),
    mimeType: firstNonEmpty(raw.mimeType, kind === 'audio' ? 'audio/mp4' : 'video/mp4'),
    container: firstNonEmpty(raw.format, 'MPEG_4').toLowerCase(),
    quality: quality || (resolvedHeight ? `${resolvedHeight}p` : kind),
    codecs: codec,
    bitrate: toInt(raw.bitrate, 0),
    // `videoOnly: false` on a Piped video stream means video and audio are muxed together.
    hasVideo: kind === 'video',
    hasAudio: kind === 'audio' || raw.videoOnly === false,
    width,
    height: resolvedHeight,
    fps: toInt(raw.fps, 0),
    size: 0,
    isHls: /hls/i.test(quality),
  }
}

function mapSubtitle(raw: NonNullable<RawStreams['subtitles']>[number], base: string): Subtitle {
  const label = firstNonEmpty(raw.name, raw.code, 'Subtitles')
  return {
    label,
    language: firstNonEmpty(raw.code),
    url: absoluteUrl(firstNonEmpty(raw.url), base),
    autoGenerated: Boolean(raw.autoGenerated),
  }
}

export class PipedApi implements ProviderApi {
  readonly id = 'piped' as const
  readonly name = 'Piped'
  readonly instance: string

  constructor(ref: PipedInstanceRef) {
    this.instance = ref.apiUrl
  }

  private get(path: string, params?: Record<string, string | undefined>): string {
    const url = joinUrl(this.instance, path)
    if (!params) return url
    const search = new URLSearchParams()
    for (const [key, value] of Object.entries(params)) {
      if (value !== undefined && value !== '') search.set(key, value)
    }
    const query = search.toString()
    return query ? `${url}?${query}` : url
  }

  async trending(region: string): Promise<VideoListItem[]> {
    const raw = await request<RawSearchItem[]>(this.get('/trending', { region }), { timeoutMs: 25000 })
    return (raw ?? []).map(mapSearchItem).filter((v) => v.id !== '')
  }

  async search(query: string, continuation: string | null): Promise<Paged<VideoListItem>> {
    const path = continuation ? '/nextpage/search' : '/search'
    const raw = await request<RawPage>(this.get(path, {
      q: query,
      filter: 'videos',
      nextpage: continuation ?? undefined,
    }), { timeoutMs: 25000 })

    const items = (raw.items ?? []).filter((i) => i.type === 'stream' || i.type === undefined)
    return {
      items: items.map(mapSearchItem).filter((v) => v.id !== ''),
      continuation: raw.nextpage || null,
    }
  }

  async suggestions(query: string): Promise<string[]> {
    const raw = await request<string[]>(this.get('/suggestions', { q: query }), { timeoutMs: 12000 })
    return (raw ?? []).filter((s) => typeof s === 'string' && s.trim() !== '')
  }

  async video(id: string): Promise<VideoDetail> {
    const raw = await request<RawStreams>(this.get(`/streams/${id}`), { timeoutMs: 30000 })
    const base = firstNonEmpty(raw.proxyUrl, this.instance)

    const videoFormats = (raw.videoStreams ?? []).map((s, i) => mapVideoFormat(s, i, base, 'video'))
    const audioFormats = (raw.audioStreams ?? []).map((s, i) =>
      mapVideoFormat({ ...s, quality: s.quality ?? s.audioQuality ?? 'audio' }, i, base, 'audio'),
    )
    const formats = [...videoFormats, ...audioFormats].filter((f) => f.url !== '')

    const muxed = formats.filter((f) => f.hasAudio && f.hasVideo)
    const videoOnly = formats.filter((f) => f.hasVideo && !f.hasAudio)
    const audioOnly = formats.filter((f) => !f.hasVideo)
    const ordered = [...muxed, ...videoOnly, ...audioOnly]

    // Degenerate instances answer 200 with stream entries that have no usable URL.
    // Surface that as a retryable failure so the caller can fail over to another instance.
    if (ordered.length === 0) {
      throw new HttpError(503, this.instance, 'Instance returned no playable streams')
    }

    return {
      id,
      title: firstNonEmpty(raw.title, 'Untitled'),
      description: firstNonEmpty(raw.description),
      thumbnail: absoluteUrl(firstNonEmpty(raw.thumbnailUrl), base),
      duration: toInt(raw.duration, UNKNOWN),
      views: toInt(raw.views, UNKNOWN),
      likes: toInt(raw.likes, 0),
      dislikes: toInt(raw.dislikes, 0),
      publishedText: firstNonEmpty(raw.uploadDate),
      published: relativeToTimestamp(raw.uploadDate),
      uploaderName: firstNonEmpty(raw.uploader),
      uploaderId: parseChannelIdFromPath(raw.uploaderUrl),
      uploaderAvatar: absoluteUrl(firstNonEmpty(raw.uploaderAvatar), base),
      uploaderVerified: Boolean(raw.uploaderVerified),
      subscriberCount: toInt(String(raw.subCountText ?? '').replace(/[^\d]/g, ''), UNKNOWN),
      live: Boolean(raw.livestream),
      hlsUrl: raw.hls ?? null,
      formats: ordered,
      subtitles: (raw.subtitles ?? []).map((s) => mapSubtitle(s, base)),
      related: (raw.relatedStreams ?? []).map(mapSearchItem).filter((v) => v.id !== ''),
    }
  }

  async comments(id: string, continuation: string | null): Promise<CommentsPage> {
    // First page is `/comments/:videoId`; later pages use the query-param nextpage form.
    const url = continuation ? this.get('/nextpage/comments', { videoId: id, nextpage: continuation }) : this.get(`/comments/${id}`)
    const raw = await request<RawComments>(url, { timeoutMs: 25000 })

    const comments: CommentItem[] = (raw.comments ?? []).map((c) => ({
      id: firstNonEmpty(c.commentId, c.author ?? 'comment'),
      author: firstNonEmpty(c.author, 'Unknown'),
      authorId: parseChannelIdFromPath(c.commentorUrl),
      avatar: firstNonEmpty(c.thumbnail),
      text: firstNonEmpty(c.commentText),
      publishedText: firstNonEmpty(c.commentedTime),
      likes: toInt(c.likeCount, 0),
      hearted: Boolean(c.hearted),
      pinned: Boolean(c.pinned),
      creatorReplied: Boolean(c.creatorReplied),
      replies: [],
    }))

    return { comments, continuation: raw.nextpage || null, disabled: Boolean(raw.disabled) }
  }

  async channel(id: string): Promise<ChannelInfo> {
    const raw = await request<RawChannel>(this.get(`/channel/${id}`), { timeoutMs: 25000 })
    const base = this.instance
    return {
      id: firstNonEmpty(raw.id, id),
      name: firstNonEmpty(raw.name, 'Unknown channel'),
      avatar: absoluteUrl(firstNonEmpty(raw.avatarUrl), base),
      banner: absoluteUrl(firstNonEmpty(raw.bannerUrl), base),
      description: firstNonEmpty(raw.description),
      subscriberCount: toInt(raw.subscriberCount, UNKNOWN),
      totalViews: UNKNOWN,
      joined: '',
      verified: Boolean(raw.verified),
      tags: [],
    }
  }

  async channelVideos(id: string, continuation: string | null): Promise<Paged<VideoListItem>> {
    // Piped has no `/channel?id=` list endpoint: the first page comes from `/channel/:id`,
    // and subsequent pages from `/nextpage/channel`.
    const raw = continuation
      ? await request<RawChannel>(this.get('/nextpage/channel', { id, nextpage: continuation }), {
          timeoutMs: 25000,
        })
      : await request<RawChannel>(this.get(`/channel/${id}`), { timeoutMs: 25000 })
    const items = (raw.relatedStreams ?? []).map(mapSearchItem).filter((v) => v.id !== '')
    // Degraded instances return channel metadata with an empty video list.
    if (!continuation && items.length === 0) {
      throw new HttpError(503, this.instance, 'Instance returned no channel videos')
    }
    return { items, continuation: raw.nextpage || null }
  }

  async channelPlaylists(_id: string, _continuation: string | null): Promise<Paged<PlaylistInfo>> {
    // Not implemented by the Piped API. Throwing a retryable error lets the failover
    // chain reach an Invidious instance, which can list channel playlists.
    throw new HttpError(503, this.instance, 'Channel playlists are not supported by Piped')
  }

  async playlist(id: string): Promise<PlaylistInfo> {
    const raw = await request<RawPlaylist>(this.get(`/playlists/${id}`), { timeoutMs: 25000 })
    const base = this.instance
    const videos = (raw.relatedStreams ?? []).map(mapSearchItem).filter((v) => v.id !== '')
    const videoCount = toInt(raw.videos, videos.length)
    // Degraded instances report a video count but return no video items.
    if (videoCount > 0 && videos.length === 0) {
      throw new HttpError(503, this.instance, 'Instance returned an empty playlist')
    }
    const info: PlaylistInfo = {
      id,
      title: firstNonEmpty(raw.name, 'Playlist'),
      thumbnail: absoluteUrl(firstNonEmpty(raw.thumbnailUrl), base),
      description: firstNonEmpty(raw.description),
      authorName: firstNonEmpty(raw.uploader),
      authorId: parseChannelIdFromPath(raw.uploaderUrl),
      authorAvatar: absoluteUrl(firstNonEmpty(raw.uploaderAvatar), base),
      videoCount,
      videos,
    }
    return info
  }

  async playlistVideos(id: string, continuation: string | null): Promise<Paged<VideoListItem>> {
    const raw = continuation
      ? await request<RawPlaylist>(this.get('/nextpage/playlists', { playlistId: id, nextpage: continuation }), {
          timeoutMs: 25000,
        })
      : await request<RawPlaylist>(this.get(`/playlists/${id}`), { timeoutMs: 25000 })
    const items = (raw.relatedStreams ?? []).map(mapSearchItem).filter((v) => v.id !== '')
    if (!continuation && items.length === 0 && toInt(raw.videos, 0) > 0) {
      throw new HttpError(503, this.instance, 'Instance returned no playlist videos')
    }
    return { items, continuation: raw.nextpage || null }
  }
}