export interface VideoListItem {
  id: string
  title: string
  thumbnail: string
  duration: number
  views: number
  viewsText: string
  publishedText: string
  published: number
  uploaderName: string
  uploaderId: string
  uploaderAvatar: string
  uploaderVerified: boolean
  live: boolean
  isShort: boolean
}

export interface VideoFormat {
  itag: number
  url: string
  mimeType: string
  container: string
  quality: string
  codecs: string
  bitrate: number
  hasVideo: boolean
  hasAudio: boolean
  width: number
  height: number
  fps: number
  size: number
  isHls: boolean
}

export interface Subtitle {
  label: string
  language: string
  url: string
  autoGenerated: boolean
}

export interface VideoDetail {
  id: string
  title: string
  description: string
  thumbnail: string
  duration: number
  views: number
  likes: number
  dislikes: number
  publishedText: string
  published: number
  uploaderName: string
  uploaderId: string
  uploaderAvatar: string
  uploaderVerified: boolean
  subscriberCount: number
  live: boolean
  hlsUrl: string | null
  formats: VideoFormat[]
  subtitles: Subtitle[]
  related: VideoListItem[]
}

export interface ChannelInfo {
  id: string
  name: string
  avatar: string
  banner: string
  description: string
  subscriberCount: number
  totalViews: number
  joined: string
  verified: boolean
  tags: string[]
}

export interface ChannelTab {
  key: 'videos' | 'playlists' | 'about'
  label: string
}

export interface PlaylistInfo {
  id: string
  title: string
  thumbnail: string
  description: string
  authorName: string
  authorId: string
  authorAvatar: string
  videoCount: number
  videos: VideoListItem[]
}

export interface CommentItem {
  id: string
  author: string
  authorId: string
  avatar: string
  text: string
  publishedText: string
  likes: number
  hearted: boolean
  pinned: boolean
  creatorReplied: boolean
  replies: CommentItem[]
}

export interface CommentsPage {
  comments: CommentItem[]
  continuation: string | null
  disabled: boolean
}

export interface Paged<T> {
  items: T[]
  continuation: string | null
}

export interface ProviderApi {
  readonly id: ProviderId
  readonly name: string
  readonly instance: string
  trending(region: string): Promise<VideoListItem[]>
  search(query: string, continuation: string | null): Promise<Paged<VideoListItem>>
  suggestions(query: string): Promise<string[]>
  video(id: string): Promise<VideoDetail>
  comments(id: string, continuation: string | null): Promise<CommentsPage>
  channel(id: string): Promise<ChannelInfo>
  channelVideos(id: string, continuation: string | null): Promise<Paged<VideoListItem>>
  channelPlaylists(id: string, continuation: string | null): Promise<Paged<PlaylistInfo>>
  playlist(id: string): Promise<PlaylistInfo>
  playlistVideos(id: string, continuation: string | null): Promise<Paged<VideoListItem>>
}

export type ProviderId = 'piped' | 'invidious'

/** `auto` allows cross-provider failover; the other values pin requests to one provider. */
export type ProviderPreference = ProviderId | 'auto'